
use_cuda: True
n_iters: 50000
n_iters_decay: 0
batch_size: 1

logging:
    output_dir: "./checkpoints/ex1/"
    wandb: False
    tensorboard: False
    log_freq: 10
    checkpoint_freq: 1000

dataset: 
    name: "DummyDataset"
    root: '.'

# gan:  
#     name: "PiCycleGAN"

# generator:  
#     name: "VnetGenerator"
#     use_memory_saving: False

# discriminator:  
#     name: "PatchGAN"
#     n_layers: 3