
use_cuda: True
n_iters: 50000
n_iters_decay: 0
batch_size: 1

logging:
    output_dir: "./checkpoints/ex1/"
    wandb: False
    tensorboard: False
    log_freq: 10
    checkpoint_freq: 1000

dataset: 
    class_name: "DummyDatasetConfig"
    root: '.'

gan:  
    class_name: "PiCycleGANConfig"

generator:  
    class_name: "VnetGeneratorConfig"
    use_memory_saving: False

discriminator:  
    class_name: "PatchGANDiscriminatorConfig"
    n_layers: 3