site_name: ganslate
  
nav:
    - Home: index.md
    - Installation: installation.md
    - Getting Started:
        - Using the command line interface: getting_started/using_cli.md
        - First run with maps to aerial photo dataset: getting_started/first_run.md

    - Tutorials:
        - Intro to Configuration: tutorials/configuration.md
        - Starting a New Project: tutorials/starting_a_new_project.md
        - Custom Dataset: tutorials/custom_dataset.md
        - Custom Architecture: tutorials/custom_architecture.md
    
    - User Guide:
        - Visualizations and logging with ganslate: user_guide/visualizations.md
        - Training, Validation, Testing, Inference: user_guide/engines.md

    - API: api/*
        
    - Community:
        - Contributing:  community/contributing.md

theme: readthedocs

markdown_extensions:
    - admonition