project_dir: ./projects/maastro_lung_proton_cbct_to_ct

train:
    mixed_precision: True
    cuda: True
    n_iters: 15000
    n_iters_decay: 15000
    batch_size: 1
    output_dir: ./checkpoints/3d_vnet
    seed: 42

    logging:
        freq: 100
        wandb:
            project: Media_Experiments_Proton
            image_filter: [0.289 ,0.40]
            run: 3d_vnet

    checkpointing:
        freq: 1000

    dataset: 
        name: CBCTtoCTDataset
        root: /workspace/train_val/train
        num_workers: 8
        patch_size: [24, 384, 384]

    gan:  
        name: CycleGAN

        generator:
            name: Vnet3D
            in_channels: 1
            down_blocks: [2, 2, 3]
            up_blocks: [3, 3, 3]

        discriminator:
            name: PatchGAN3D
            n_layers: 2
            in_channels: 1

        optimizer:
            lambda_A: 5.0
            lambda_B: 5.0
            lambda_identity: 0.0
            proportion_ssim: 0.0
            lr_D: 0.0002
            lr_G: 0.0004

    metrics: 
        discriminator_evolution: True
        ssim: True
    
val:
    freq: 1000

    multi_dataset:
        lungs:
            name: CBCTtoCTValTestDataset
            root: /workspace/train_val/val
        
        phantoms:
            name: CBCTtoCTValTestDataset
            root: /workspace/train_val/val_phantom

    sliding_window:
        window_size: ${train.dataset.patch_size}
