
use_cuda: True
n_iters: 50000
n_iters_decay: 0
batch_size: 1

logging:
    checkpoint_dir: "./checkpoints/ex1/"
    wandb: None
    tensorboard: False
    log_freq: 10
    checkpoint_freq: 1000

dataset: 
    name: "DummyDataset"
    root: '.'

gan:  
    name: "PiCycleGAN"

generator:  
    name: "Vnet3D"
    use_memory_saving: False

discriminator:  
    name: "PatchGAN3D"
    n_layers: 3