project_dir: 
    - ./projects/maastro_lung_proton_cbct_to_ct
    - ./modules
train:
    mixed_precision: True
    cuda: True
    n_iters: 15000
    n_iters_decay: 15000
    batch_size: 1
    output_dir: /work/vq218944/checkpoints/adaptive_lambda
    seed: 42

    logging:
        freq: 100
        wandb:
            project: Thesis_CBCT
            image_filter: [0.289 ,0.40]
            run: adaptive_lambda

    checkpointing:
        freq: 2000

    dataset: 
        name: CBCTtoCTDataset
        root: /work/vq218944/maastro_physics/train
        num_workers: 8
        patch_size: [16, 320, 320]

    gan:  
        name: "AdaptiveCycleGAN"

        generator:
            name: Vnet3D
            in_channels: 1
            out_channels: 1
            down_blocks: [2, 2, 3]
            up_blocks: [3, 3, 3]

        discriminator:
            name: PatchGAN3D
            n_layers: 2
            in_channels: 1

        optimizer:
            lambda_AB: 5.0
            lambda_BA: 5.0
            lambda_identity: 0.0
            proportion_ssim: 0.0
            lr_D: 0.0002
            lr_G: 0.0004

        adaptive_training:
            adaptive_lambda: True
            patience: 10
            freq: 100
            warmup_iter: 5000
            change_rate: 0.01           

    metrics: 
        discriminator_evolution: True
        ssim: True
    
val:
    freq: 2000
    start_after: 10000

    multi_dataset:
        lungs:
            name: CBCTtoCTValTestDataset
            root: /work/vq218944/maastro_physics/val
        
        phantoms:
            name: CBCTtoCTValTestDataset
            root:  /work/vq218944/maastro_physics/val_phantom

    sliding_window:
        window_size: ${train.dataset.patch_size}
