use_cuda: False
n_iters: 100
n_iters_decay: 0
batch_size: 1

dataset: 
    class_name: "CTDatasetConfig"
    root: "./IGNORE/dataset/"

gan:  
    class_name: "Cycle3DGANConfig"

    generator:  
        class_name: "VnetGeneratorConfig"

    discriminator:  
        class_name: "PatchGANDiscriminatorConfig"

logging:
    wandb: True