use_cuda: True
n_iters: 500000
n_iters_decay: 0
batch_size: 2

dataset: 
    class_name: "CTNRRDDatasetConfig"
    root: "/work/ft002207/CT_CBCT_dataset_resampled"
    hounsfield_units_range: 
        - -1000
        - 2000
    num_workers: 8
    patch_size:
        - 32
        - 192
        - 192
gan:  
    class_name: "Cycle3DGANConfig"

    generator:  
        class_name: "VnetGeneratorConfig"

    discriminator:  
        class_name: "PatchGANDiscriminatorConfig"

logging:
    wandb: True
    log_freq: 10
    checkpoint_freq: 10000