use_cuda: False
n_epochs: 1
n_epochs_decay: 0
batch_size: 1

dataset: 
    class_name: "CTDatasetConfig"
    root: "./IGNORE/dataset/"

gan:  
    class_name: "Cycle3DGANConfig"

    generator:  
        class_name: "PiVnetGeneratorConfig"

    discriminator:  
        class_name: "PatchGANDiscriminatorConfig"

logging:
    wandb: True