project_dir: "./projects/nki_cervix_cbct_to_ct"
cuda: True
batch_size: 1

logging:
    output_dir: ./checkpoints/cbct_ex3/
    inference_dir: ./results
   
dataset: 
    name: "CBCTtoCTInferenceDataset"
    root: /home/rt/workspace_suraj/s.pai/test_resampled
    hounsfield_units_range: [-1024, 2048]
    num_workers: 4
    
gan:  
    name: "PiCycleGAN"


sliding_window:
  window_size: [16, 128, 128]

generator:
  name: Vnet3D
  in_channels: 1
  use_memory_saving: False
  use_inverse: True
  is_separable: False
  down_blocks: [2, 2, 3]
  up_blocks: [3, 3, 3]

