project_dir: "./projects/nki_cervix_cbct_to_ct/datasets"

train:
    cuda: True
    n_iters: 15000
    n_iters_decay: 15000
    batch_size: 1
    output_dir: /midagan/checkpoints/baseline_2d
    seed: 42

    logging:
        freq: 1
        wandb:
            project: "Media_Experiments"
            image_filter: [0.289 ,0.40]

    checkpointing:
        freq: 1000

    dataset: 
        name: "CBCTtoCT2DDataset"
        root: /data/train
        num_workers: 4
        image_size: [384, 384]
        enable_masking: True

    gan:  
        name: "CycleGAN"

        generator:
            name: Unet2D
            in_channels: 1

        discriminator:
            name: "PatchGAN2D"
            n_layers: 2
            in_channels: 1

        optimizer:
            lambda_A: 5.0
            lambda_B: 5.0
            lambda_identity: 0.0
            proportion_ssim: 0.0
            lr_D: 0.0001
            lr_G: 0.0002

    metrics: 
        discriminator_evolution: True
        ssim: True
    
val:
    freq: 1000
    dataset: 
    -   name: CBCTtoCTValDataset
        root:  /data/valid
        
    -   name: ElektaPhantomDataset
        root:  /data/phantom

    sliding_window:
        window_size: "${train.dataset.image_size}"

test:
    dataset: "${val.datasets}"
    sliding_window: "${val.sliding_window}"

