use_cuda: True
n_iters: 50000
n_iters_decay: 0
batch_size: 1

logging:
    output_dir: "./projects/brats_flair_to_t1w/checkpoints/experiment1/"
    wandb: False
    tensorboard: False
    log_freq: 10
    checkpoint_freq: 1000

dataset: 
    class_name: "BratsDatasetConfig"
    root: "/work/ft002207/Task01_BrainTumour/imagesTr/"
    num_workers: 8
    patch_size: [32, 240, 240]
gan:  
    class_name: "PiCycleGANConfig"

    generator:  
        class_name: "VnetGeneratorConfig"

    discriminator:  
        class_name: "PatchGANDiscriminatorConfig"
        n_layers: 3

logging:
    wandb: False
    log_freq: 1
    checkpoint_freq: 1000